/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

//#include "stm32f4xx.h"
#include "stm32f401_spi.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void SPI2_GPIOInits(void)
{
     GPIO_Handler gpio_spi1;

		gpio_spi1.GPIOX = GPIOA;
		gpio_spi1.GPIO_Pin_Conf.PinMode   = GPIO_MODE_ALTFN;
		gpio_spi1.GPIO_Pin_Conf.PinAltFn  = 5 ;
	    gpio_spi1.GPIO_Pin_Conf.PinSpeed  = GPIO_OUTSPEED_HIGH ;
	    gpio_spi1.GPIO_Pin_Conf.PinOPTYP  = GPIO_OUTYPE_PP ;
	    gpio_spi1.GPIO_Pin_Conf.PinPUPDR  = GPIO_PIN_PUPD_NO ;


//SCLK
	    gpio_spi1.GPIO_Pin_Conf.PinNum    = GPIO_PIN_5;
        GPIO_init(&gpio_spi1);

//MOSI      
        gpio_spi1.GPIO_Pin_Conf.PinNum    = GPIO_PIN_7;
        GPIO_init(&gpio_spi1);
// //MISO       
//         gpio_spi1.GPIO_Pin_Conf.PinNum    = GPIO_PIN_6;
//         GPIO_init(&gpio_spi1);
// //NSS       
//         gpio_spi1.GPIO_Pin_Conf.PinNum    = GPIO_PIN_4;
//         GPIO_init(&gpio_spi1);
}
void SPI2_Inits(void)
{
   SPI_Handler hspi1;

        hspi1.pSPI=SPI1;
        hspi1.SpiConfig.SPI_BusConfg = SPI_BUS_CONFIG_FD;
        hspi1.SpiConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
        hspi1.SpiConfig.SPI_Speed = SPI_SPEED_DIV2 ;
        hspi1.SpiConfig.SPI_DFF = SPI_DFF_8_BITS;
        hspi1.SpiConfig.SPI_CPOL = SPI_CPOL_LOW;
        hspi1.SpiConfig.SPI_CPHA = SPI_CPHA_LOW;
        hspi1.SpiConfig.SPI_SSM = SPI_SSM_EN;

        SPI_init(&hspi1);

}

int main(void)
{


char user_data[] = "Hello world";
SPI2_GPIOInits();

	//This function is used to initialize the SPI2 peripheral parameters
	SPI2_Inits();

	//this makes NSS signal internally high and avoids MODF error
	SPI_ssi_conf(SPI1,ENABLE);

	//enable the SPI2 peripheral
	SPI_PeripheralControl(SPI1,ENABLE);

	//to send data
	SPI_SendData(SPI1,(uint8_t*)user_data,strlen(user_data));

	//lets confirm SPI is not busy
	while( GetFlagStatus(SPI1,SPI_BSY_FLAG) );

	//Disable the SPI2 peripheral
	SPI_PeripheralControl(SPI1,DISABLE);

    while(1);

	return 0;

}




